---
stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - mvn clean package
    - sudo docker build -t gitlab.sslsecure.website:5050/root/kick-scooter-trip:trip .
    - sudo docker push gitlab.sslsecure.website:5050/root/kick-scooter-trip:trip
  when: manual

deploy:
  stage: deploy
  script:
    - scp -r ~/env ~/docker-compose.yml ~/deploy.sh $USERNAME@$IP:/var/kick-scooter
  after_script:
    - docker image prune -a -f &>/dev/null
  when: manual
