---
stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - cp /home/sumo_credentials.txt ./sumo_credentials.txt    
    - mvn clean package
    - sudo docker build -t gitlab.sslsecure.website:5050/root/kick-scooter-trip:trip .
    - sudo docker push gitlab.sslsecure.website:5050/root/kick-scooter-trip:trip
  only:
    - demo3

deploy:
  stage: deploy
  script:
    - ssh $USERNAME@$IP "cd /var/ && sudo bash /var/deploy.sh"
  after_script:
    - docker image prune -a -f &>/dev/null
  only:
    - demo3
